--INSERTING ACCOUNTS
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, PIN, OPENING_BALANCE, OVERDRAFT, ACTIVE) VALUES ('123456789',1234,800,200, true);
INSERT INTO ACCOUNT (ACCOUNT_NUMBER, PIN, OPENING_BALANCE, OVERDRAFT, ACTIVE) VALUES ('987654321',4321,1230,150, true);

--INSERTING BANKNOTES QUANTITIES
INSERT INTO BANKNOTES (CREATION_DATE, BANKNOTE_VALUE, QUANTITY) VALUES (CURRENT_TIMESTAMP, 50,10);
INSERT INTO BANKNOTES (CREATION_DATE, BANKNOTE_VALUE, QUANTITY) VALUES (CURRENT_TIMESTAMP, 20,30);
INSERT INTO BANKNOTES (CREATION_DATE, BANKNOTE_VALUE, QUANTITY) VALUES (CURRENT_TIMESTAMP, 10,30);
INSERT INTO BANKNOTES (CREATION_DATE, BANKNOTE_VALUE, QUANTITY) VALUES (CURRENT_TIMESTAMP, 5,20);